1134 refresh timeseries
Deltares/fews-web-oc pull request #1136
Opened 2024-12-17 13:07 UTC by amarkensteijn

## Pull Request Template

### Description

Please provide a brief description of the changes made in this pull request.

### Screenshots (if applicable)

If there are any visual changes, please attach screenshots here.

### Link to documentation (if applicable)

Add link to public Github pages (only documentation about configuration)

### Checklist
- [ ] Make the title short and concise
- [ ] Select the correct label to include it in the release notes:
    - `rel: new feature`
    - `rel: improvement`
    - `rel: fixes`
    - `rel: ignore`
    Select to `rel: ignore` if this pull request fixes a New Feature or Improvement in the coming release. Update related Pull Request.
- [ ] Update documentation.
- [ ] Update tests.

2024-12-17 13:09 UTC, amarkensteijn commented
Currently, the charts get recreated every time the data changes, which lead to frequent 'flickering' of the chart (see also [this comment](https://issuetracker.deltares.nl/browse/DWO-816?focusedId=970518&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-970518)). Created [this issue](https://github.com/Deltares/fews-web-oc-charts/issues/120) to look into this.

2024-12-20 14:44 UTC, amarkensteijn commented
The interval / automatic refresh still needs to be implemented for the elevation charts

2025-01-09 12:41 UTC, amarkensteijn commented
It still flickers sometimes. As far as I've been able to determine, this is due to the `v-show` and the `LoadingOverlay` based on the `isLoading` prop. We should move the loading indicator to each indiviual series, e.g. in the legend tag. We could consider an initial loader indicator on the full chart panel when opening it for the first time, untill the chart config have loaded or untill as least one series has data. Something like this is done for the RWsOS viewer

2025-01-09 15:15 UTC, amarkensteijn commented
> The interval / automatic refresh still needs to be implemented for the elevation charts

Has been fixed

2025-03-26 10:09 UTC, amarkensteijn commented
> Currently, the charts get recreated every time the data changes, which lead to frequent 'flickering' of the chart (see also [this comment](https://issuetracker.deltares.nl/browse/DWO-816?focusedId=970518&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-970518)). Created [this issue](https://github.com/Deltares/fews-web-oc-charts/issues/120) to look into this.

Has been fixed

2025-03-26 10:10 UTC, amarkensteijn commented
> It still flickers sometimes. As far as I've been able to determine, this is due to the `v-show` and the `LoadingOverlay` based on the `isLoading` prop. We should move the loading indicator to each indiviual series, e.g. in the legend tag. We could consider an initial loader indicator on the full chart panel when opening it for the first time, untill the chart config have loaded or untill as least one series has data. Something like this is done for the RWsOS viewer

Has been fixed by removing the loading overlay. It might be nice to have some kind of loading indicator, somewhere, but we should pick that up in a separate issue

2025-03-26 12:28 UTC, hvangeffen requested changes
The charts sometimes don't update when switching locations on the map.

2025-03-27 12:37 UTC, amarkensteijn commented
> The charts sometimes don't update when switching locations on the map.

Has been fixed by removing the debounced on the loading times series ids

2025-03-27 13:32 UTC, hvangeffen approved these changes

2025-03-27 14:39 UTC, merged